// Turn the analysis into three things:
//  1. BLUEPRINT.md  — an owner's manual in plain English
//  2. an "AI context" block to paste into CLAUDE.md / .cursorrules, so your AI
//     builder starts every session knowing the app instead of re-reading it
//  3. .env.example  — every setting the app needs, names only, never values

const list = (items, empty = '_None found._') => (items.length ? items.map((i) => `- ${i}`).join('\n') : empty);

export function ownersManual(a) {
  const pub = a.env.filter((e) => e.public), priv = a.env.filter((e) => !e.public);
  const L = [];
  L.push(`# ${a.name}: owner's manual`, '');
  L.push(`Made by Blueprint from the app's code. ${a.fileCount} files looked at. Nothing was sent anywhere.`, '');
  L.push('## What it is', '');
  L.push(`- **Built with:** ${a.framework}`);
  L.push(`- **Runs on:** ${a.deploy.join(', ') || 'not detected'}`);
  L.push(`- **Outside services it depends on:** ${a.services.join(', ') || 'none detected'}`, '');
  if (a.warnings.length) { L.push('## Fix these first', '', list(a.warnings), ''); }
  L.push(`## Pages people can visit (${a.pages.length})`, '', list(a.pages.map((p) => `\`${p}\``)), '');
  L.push(`## Behind-the-scenes endpoints (${a.apis.length})`, '', 'These run on the server. Anything that charges money, sends email or changes data usually lives here.', '', list(a.apis.map((p) => `\`${p}\``)), '');
  if (a.tables.length || a.buckets.length || a.rpcs.length) {
    L.push('## Where the data lives', '');
    if (a.tables.length) L.push(`**Database tables (${a.tables.length})** — each should have Row Level Security on:`, '', list(a.tables.map((t) => `\`${t.table}\` — used in ${t.files.length} file${t.files.length === 1 ? '' : 's'}`)), '');
    if (a.buckets.length) L.push('**File storage buckets:**', '', list(a.buckets.map((b) => `\`${b}\``)), '');
    if (a.rpcs.length) L.push('**Database functions:**', '', list(a.rpcs.map((r) => `\`${r}\``)), '');
  }
  L.push(`## Settings the app needs (${a.env.length})`, '');
  L.push('Set these on your host (for Vercel: Settings → Environment Variables). A full list with no values is in `.env.example`.', '');
  if (priv.length) L.push('**Server-only (keep secret):**', '', list(priv.map((e) => `\`${e.name}\``)), '');
  if (pub.length) L.push('**Public (the browser can see these, so never put a secret here):**', '', list(pub.map((e) => `\`${e.name}\``)), '');
  if (a.hosts.length) L.push('## Other websites it talks to', '', list(a.hosts.map((h) => `\`${h}\``)), '');
  const scripts = Object.entries(a.scripts);
  if (scripts.length) L.push('## Commands', '', list(scripts.map(([k, v]) => `\`npm run ${k}\` — ${v}`)), '');
  if (a.workflows.length) L.push('## Automatic jobs (GitHub Actions)', '', list(a.workflows.map((w) => `\`${w}\``)), '');
  L.push('## How the code is laid out', '', list(a.folders.map(([d, n]) => `\`${d}\` — ${n} file${n === 1 ? '' : 's'}`)), '');
  if (a.biggest.length) L.push('**Biggest code files** (the ones most likely to need splitting up):', '', list(a.biggest.map((f) => `\`${f.path}\` — ${(f.size / 1024).toFixed(0)} KB`)), '');
  return L.join('\n');
}

// Short on purpose: this gets read at the start of every AI session.
export function aiContext(a) {
  const L = ['## App map (generated by Blueprint — read this before opening files)', ''];
  L.push(`Stack: ${a.framework}${a.deploy.length ? ` on ${a.deploy.join('/')}` : ''}. Services: ${a.services.join(', ') || 'none'}.`);
  if (a.pages.length) L.push(`Pages: ${a.pages.slice(0, 40).join(', ')}${a.pages.length > 40 ? ` (+${a.pages.length - 40} more)` : ''}`);
  if (a.apis.length) L.push(`API routes: ${a.apis.slice(0, 40).join(', ')}`);
  if (a.tables.length) L.push(`DB tables: ${a.tables.map((t) => t.table).join(', ')}`);
  if (a.buckets.length) L.push(`Storage buckets: ${a.buckets.join(', ')}`);
  if (a.env.length) L.push(`Env vars: ${a.env.map((e) => e.name + (e.public ? ' (public)' : '')).join(', ')}`);
  L.push(`Folders: ${a.folders.map(([d, n]) => `${d} (${n})`).join(', ')}`);
  L.push('', 'Rules: search for the file you need instead of reading whole folders; make small edits; never move a server-only env var into a public one.');
  return L.join('\n');
}

export function envExample(a) {
  if (!a.env.length) return '# No environment variables found.\n';
  const L = ['# Every setting this app reads. Fill in values on your host, never commit real ones.', ''];
  const priv = a.env.filter((e) => !e.public), pub = a.env.filter((e) => e.public);
  if (priv.length) { L.push('# Server-only (secret)'); for (const e of priv) L.push(`${e.name}=`); L.push(''); }
  if (pub.length) { L.push('# Public (visible in the browser; no secrets here)'); for (const e of pub) L.push(`${e.name}=`); L.push(''); }
  return L.join('\n');
}
